### ISSUE TITLE
Tabs disappears when logged in as a user

### ISSUE THREAD

**Issue by obrianimo** [obrianimo/AGRA-KMS#2]
Dear John,
AS indicated I have noticed that when a user is logged in the tabs disappears.

Please see the snapshot and assist

![tabs disappears 01](https://user-images.githubusercontent.com/32592617/42581710-ef8cfe80-851c-11e8-8b78-de31ed763501.png)
![tabs disappears 02](https://user-images.githubusercontent.com/32592617/42581713-efc503ac-851c-11e8-98c2-f6e623e6c323.png)

**Comment by fereira** [comment]
Comments on fix inhttps://github.com/obrianimo/AGRA-KMS/issues/5

**Comment by obrianimo** [comment]
This was resolved by John
