### ISSUE TITLE
Replace the language button and content with the Unit/Department Names

### ISSUE THREAD

**Issue by obrianimo** [obrianimo/AGRA-KMS#3]
Hi John,

Please look into this too for us, and let me know once active.

Regards,
Ben

**Comment by fereira** [comment]
Just so you know.  When you assign an issue to me (or I assign one to you) it automatically sends an email message with a link to the issue.

**Comment by obrianimo** [comment]
That's great!

**Comment by fereira** [comment]
Jane would prefer to leave the Language facet and replace the Value Chain button with "Collections"
